[
  {
    "id": 1,
    "name": "Побудувати Окоп",
    "description": "Потрібно: Побудувати 1 од. 'Окоп'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 4,
    "level_reward_points": 0.3,
    "currency_reward": 2
  },
  {
    "id": 2,
    "name": "Побудувати Окоп",
    "description": "Потрібно: Побудувати 2 од. 'Окоп'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 8,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 3,
    "name": "Побудувати Окоп",
    "description": "Потрібно: Побудувати 3 од. 'Окоп'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 3,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 4,
    "name": "Побудувати Окоп",
    "description": "Потрібно: Побудувати 4 од. 'Окоп'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 4,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 5,
    "name": "Побудувати Барикаду",
    "description": "Потрібно: Побудувати 1 од. 'Барикаду'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 6,
    "level_reward_points": 0.4,
    "currency_reward": 2
  },
  {
    "id": 6,
    "name": "Побудувати Мега барикаду",
    "description": "Потрібно: Побудувати 1 од. 'Мега барикаду'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 8,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 7,
    "name": "Побудувати Мега барикаду",
    "description": "Потрібно: Побудувати 2 од. 'Мега барикаду'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 8,
    "name": "Побудувати Колючий дріт",
    "description": "Потрібно: Побудувати 1 од. 'Колючий дріт'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 6,
    "level_reward_points": 0.4,
    "currency_reward": 2
  },
  {
    "id": 9,
    "name": "Побудувати Колючий дріт",
    "description": "Потрібно: Побудувати 2 од. 'Колючий дріт'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 10,
    "name": "Побудувати Вежу",
    "description": "Потрібно: Побудувати 1 од. 'Вежу'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 8,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 11,
    "name": "Побудувати Вежу",
    "description": "Потрібно: Побудувати 2 од. 'Вежу'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 12,
    "name": "Побудувати Турель",
    "description": "Потрібно: Побудувати 1 од. 'Турель'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 10,
    "level_reward_points": 0.4,
    "currency_reward": 4
  },
  {
    "id": 13,
    "name": "Побудувати Турель",
    "description": "Потрібно: Побудувати 2 од. 'Турель'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 14,
    "name": "Знищити на підконтрольному секторі ворога",
    "description": "Потрібно: Знищити на підконтрольному секторі 1 од. 'ворога'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 15,
    "level_reward_points": 0.5,
    "currency_reward": 5
  },
  {
    "id": 15,
    "name": "Знищити на підконтрольному секторі ворога",
    "description": "Потрібно: Знищити на підконтрольному секторі 2 од. 'ворога'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 2,
    "main_reward": 30,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 16,
    "name": "Знищити на підконтрольному секторі ворога",
    "description": "Потрібно: Знищити на підконтрольному секторі 3 од. 'ворога'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 3,
    "main_reward": 45,
    "level_reward_points": 0.8,
    "currency_reward": 15
  },
  {
    "id": 17,
    "name": "Знищити на підконтрольному секторі ворога",
    "description": "Потрібно: Знищити на підконтрольному секторі 4 од. 'ворога'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 4,
    "main_reward": 60,
    "level_reward_points": 0.9,
    "currency_reward": 20
  },
  {
    "id": 18,
    "name": "Знищити на підконтрольному секторі ворога",
    "description": "Потрібно: Знищити на підконтрольному секторі 5 од. 'ворога'",
    "m_class": "Захист",
    "level": 3,
    "target_progress": 5,
    "main_reward": 75,
    "level_reward_points": 1.1,
    "currency_reward": 25
  },
  {
    "id": 19,
    "name": "Знищити на підконтрольному секторі мутантів",
    "description": "Потрібно: Знищити на підконтрольному секторі 1 од. 'мутантів'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 9,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 20,
    "name": "Знищити на підконтрольному секторі мутантів",
    "description": "Потрібно: Знищити на підконтрольному секторі 2 од. 'мутантів'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 18,
    "level_reward_points": 0.6,
    "currency_reward": 6
  },
  {
    "id": 21,
    "name": "Знищити на підконтрольному секторі мутантів",
    "description": "Потрібно: Знищити на підконтрольному секторі 3 од. 'мутантів'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 3,
    "main_reward": 27,
    "level_reward_points": 0.7,
    "currency_reward": 9
  },
  {
    "id": 22,
    "name": "Знищити на підконтрольному секторі мутантів",
    "description": "Потрібно: Знищити на підконтрольному секторі 4 од. 'мутантів'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 4,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 23,
    "name": "Знищити на підконтрольному секторі мутантів",
    "description": "Потрібно: Знищити на підконтрольному секторі 5 од. 'мутантів'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 5,
    "main_reward": 45,
    "level_reward_points": 0.8,
    "currency_reward": 15
  },
  {
    "id": 24,
    "name": "Придбати броню",
    "description": "Потрібно: Придбати 1 од. 'броню'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 6,
    "level_reward_points": 0.4,
    "currency_reward": 2
  },
  {
    "id": 25,
    "name": "Придбати броню",
    "description": "Потрібно: Придбати 2 од. 'броню'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 26,
    "name": "Придбати броню",
    "description": "Потрібно: Придбати 3 од. 'броню'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 3,
    "main_reward": 18,
    "level_reward_points": 0.6,
    "currency_reward": 6
  },
  {
    "id": 27,
    "name": "Придбати броню",
    "description": "Потрібно: Придбати 4 од. 'броню'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 4,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 28,
    "name": "Захопити сектори",
    "description": "Потрібно: Захопити 3 од. 'сектори'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 3,
    "main_reward": 9,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 29,
    "name": "Захопити сектори",
    "description": "Потрібно: Захопити 4 од. 'сектори'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 4,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 30,
    "name": "Захопити сектори",
    "description": "Потрібно: Захопити 5 од. 'сектори'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 5,
    "main_reward": 15,
    "level_reward_points": 0.5,
    "currency_reward": 5
  },
  {
    "id": 31,
    "name": "Захопити сектори",
    "description": "Потрібно: Захопити 6 од. 'сектори'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 6,
    "main_reward": 18,
    "level_reward_points": 0.6,
    "currency_reward": 6
  },
  {
    "id": 32,
    "name": "Відремонтувати броню персонажа",
    "description": "Потрібно: Відремонтувати 1 од. 'броню персонажа'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 9,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 33,
    "name": "Відремонтувати броню персонажа",
    "description": "Потрібно: Відремонтувати 2 од. 'броню персонажа'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 18,
    "level_reward_points": 0.6,
    "currency_reward": 6
  },
  {
    "id": 34,
    "name": "Відремонтувати броню персонажа",
    "description": "Потрібно: Відремонтувати 3 од. 'броню персонажа'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 3,
    "main_reward": 27,
    "level_reward_points": 0.7,
    "currency_reward": 9
  },
  {
    "id": 35,
    "name": "Відремонтувати броню персонажа",
    "description": "Потрібно: Відремонтувати 4 од. 'броню персонажа'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 4,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 36,
    "name": "Відремонтувати броню",
    "description": "Потрібно: Відремонтувати 1 од. 'броню'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 9,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 37,
    "name": "Відремонтувати броню",
    "description": "Потрібно: Відремонтувати 2 од. 'броню'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 18,
    "level_reward_points": 0.6,
    "currency_reward": 6
  },
  {
    "id": 38,
    "name": "Відремонтувати броню",
    "description": "Потрібно: Відремонтувати 3 од. 'броню'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 3,
    "main_reward": 27,
    "level_reward_points": 0.7,
    "currency_reward": 9
  },
  {
    "id": 39,
    "name": "Відремонтувати броню",
    "description": "Потрібно: Відремонтувати 4 од. 'броню'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 4,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 40,
    "name": "Полікувати персонажа",
    "description": "Потрібно: Полікувати 1 од. 'персонажа'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 41,
    "name": "Полікувати персонажа",
    "description": "Потрібно: Полікувати 2 од. 'персонажа'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 42,
    "name": "Полікувати персонажа",
    "description": "Потрібно: Полікувати 3 од. 'персонажа'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 3,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 43,
    "name": "Нанести шкоду з турелі ворогу",
    "description": "Потрібно: Нанести шкоду з турелі 1 од. 'ворогу'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 44,
    "name": "Нанести шкоду з турелі ворогу",
    "description": "Потрібно: Нанести шкоду з турелі 2 од. 'ворогу'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 25,
    "level_reward_points": 0.7,
    "currency_reward": 9
  },
  {
    "id": 45,
    "name": "Нанести шкоду з турелі ворогу",
    "description": "Потрібно: Нанести шкоду з турелі 3 од. 'ворогу'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 3,
    "main_reward": 37,
    "level_reward_points": 0.7,
    "currency_reward": 13
  },
  {
    "id": 46,
    "name": "Нанести шкоду з турелі ворогу",
    "description": "Потрібно: Нанести шкоду з турелі 4 од. 'ворогу'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 4,
    "main_reward": 50,
    "level_reward_points": 0.8,
    "currency_reward": 17
  },
  {
    "id": 47,
    "name": "Нанести шкоду з турелі ворогу",
    "description": "Потрібно: Нанести шкоду з турелі 5 од. 'ворогу'",
    "m_class": "Захист",
    "level": 3,
    "target_progress": 5,
    "main_reward": 62,
    "level_reward_points": 1,
    "currency_reward": 21
  },
  {
    "id": 48,
    "name": "Нанести шкоду з турелі мутантам",
    "description": "Потрібно: Нанести шкоду з турелі 1 од. 'мутантам'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 1,
    "main_reward": 7,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 49,
    "name": "Нанести шкоду з турелі мутантам",
    "description": "Потрібно: Нанести шкоду з турелі 2 од. 'мутантам'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 2,
    "main_reward": 15,
    "level_reward_points": 0.5,
    "currency_reward": 5
  },
  {
    "id": 50,
    "name": "Нанести шкоду з турелі мутантам",
    "description": "Потрібно: Нанести шкоду з турелі 3 од. 'мутантам'",
    "m_class": "Захист",
    "level": 1,
    "target_progress": 3,
    "main_reward": 22,
    "level_reward_points": 0.6,
    "currency_reward": 8
  },
  {
    "id": 51,
    "name": "Нанести шкоду з турелі мутантам",
    "description": "Потрібно: Нанести шкоду з турелі 4 од. 'мутантам'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 4,
    "main_reward": 30,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 52,
    "name": "Нанести шкоду з турелі мутантам",
    "description": "Потрібно: Нанести шкоду з турелі 5 од. 'мутантам'",
    "m_class": "Захист",
    "level": 2,
    "target_progress": 5,
    "main_reward": 37,
    "level_reward_points": 0.7,
    "currency_reward": 13
  },
  {
    "id": 53,
    "name": "Вбити NPC",
    "description": "Потрібно: Вбити 1 од. 'NPC'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 54,
    "name": "Вбити NPC",
    "description": "Потрібно: Вбити 2 од. 'NPC'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 2,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 55,
    "name": "Вбити NPC",
    "description": "Потрібно: Вбити 3 од. 'NPC'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 3,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 56,
    "name": "Вбити NPC",
    "description": "Потрібно: Вбити 4 од. 'NPC'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 4,
    "main_reward": 48,
    "level_reward_points": 0.8,
    "currency_reward": 16
  },
  {
    "id": 57,
    "name": "Вбити Ігрових персонажів",
    "description": "Потрібно: Вбити 1 од. 'Ігрових персонажів'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 15,
    "level_reward_points": 0.5,
    "currency_reward": 5
  },
  {
    "id": 58,
    "name": "Вбити Ігрових персонажів",
    "description": "Потрібно: Вбити 2 од. 'Ігрових персонажів'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 2,
    "main_reward": 30,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 59,
    "name": "Вбити Ігрових персонажів",
    "description": "Потрібно: Вбити 3 од. 'Ігрових персонажів'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 3,
    "main_reward": 45,
    "level_reward_points": 0.8,
    "currency_reward": 15
  },
  {
    "id": 60,
    "name": "Вбити Ігрових персонажів",
    "description": "Потрібно: Вбити 4 од. 'Ігрових персонажів'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 4,
    "main_reward": 60,
    "level_reward_points": 0.9,
    "currency_reward": 20
  },
  {
    "id": 61,
    "name": "Вбити Ігрових персонажів",
    "description": "Потрібно: Вбити 5 од. 'Ігрових персонажів'",
    "m_class": "Атака",
    "level": 3,
    "target_progress": 5,
    "main_reward": 75,
    "level_reward_points": 1.1,
    "currency_reward": 25
  },
  {
    "id": 62,
    "name": "Знищити Будівлі",
    "description": "Потрібно: Знищити 1 од. 'Будівлі'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 18,
    "level_reward_points": 0.6,
    "currency_reward": 6
  },
  {
    "id": 63,
    "name": "Знищити Будівлі",
    "description": "Потрібно: Знищити 2 од. 'Будівлі'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 2,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 64,
    "name": "Знищити Будівлі",
    "description": "Потрібно: Знищити 3 од. 'Будівлі'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 3,
    "main_reward": 54,
    "level_reward_points": 0.8,
    "currency_reward": 18
  },
  {
    "id": 65,
    "name": "Знищити Будівлі",
    "description": "Потрібно: Знищити 4 од. 'Будівлі'",
    "m_class": "Атака",
    "level": 3,
    "target_progress": 4,
    "main_reward": 72,
    "level_reward_points": 1.1,
    "currency_reward": 24
  },
  {
    "id": 66,
    "name": "Знищити Транспорт",
    "description": "Потрібно: Знищити 1 од. 'Транспорт'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 18,
    "level_reward_points": 0.6,
    "currency_reward": 6
  },
  {
    "id": 67,
    "name": "Знищити Транспорт",
    "description": "Потрібно: Знищити 2 од. 'Транспорт'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 2,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 68,
    "name": "Знищити Транспорт",
    "description": "Потрібно: Знищити 3 од. 'Транспорт'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 3,
    "main_reward": 54,
    "level_reward_points": 0.8,
    "currency_reward": 18
  },
  {
    "id": 69,
    "name": "Знищити Турель",
    "description": "Потрібно: Знищити 1 од. 'Турель'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 21,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 70,
    "name": "Знищити Турель",
    "description": "Потрібно: Знищити 2 од. 'Турель'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 2,
    "main_reward": 42,
    "level_reward_points": 0.7,
    "currency_reward": 14
  },
  {
    "id": 71,
    "name": "Знищити Техніку",
    "description": "Потрібно: Знищити 1 од. 'Техніку'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 15,
    "level_reward_points": 0.5,
    "currency_reward": 5
  },
  {
    "id": 72,
    "name": "Знищити Техніку",
    "description": "Потрібно: Знищити 2 од. 'Техніку'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 2,
    "main_reward": 30,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 73,
    "name": "Знищити Техніку",
    "description": "Потрібно: Знищити 3 од. 'Техніку'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 3,
    "main_reward": 45,
    "level_reward_points": 0.8,
    "currency_reward": 15
  },
  {
    "id": 74,
    "name": "Знищити Техніку",
    "description": "Потрібно: Знищити 4 од. 'Техніку'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 4,
    "main_reward": 60,
    "level_reward_points": 0.9,
    "currency_reward": 20
  },
  {
    "id": 75,
    "name": "Знищити Захисні споруди",
    "description": "Потрібно: Знищити 1 од. 'Захисні споруди'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 76,
    "name": "Знищити Захисні споруди",
    "description": "Потрібно: Знищити 2 од. 'Захисні споруди'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 2,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 77,
    "name": "Знищити Захисні споруди",
    "description": "Потрібно: Знищити 3 од. 'Захисні споруди'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 3,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 78,
    "name": "Знищити Захисні споруди",
    "description": "Потрібно: Знищити 4 од. 'Захисні споруди'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 4,
    "main_reward": 48,
    "level_reward_points": 0.8,
    "currency_reward": 16
  },
  {
    "id": 79,
    "name": "Побудувати Радіовежу",
    "description": "Потрібно: Побудувати 1 од. 'Радіовежу'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 80,
    "name": "Застосувати Артилерію",
    "description": "Потрібно: Застосувати 1 од. 'Артилерію'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 10,
    "level_reward_points": 0.4,
    "currency_reward": 4
  },
  {
    "id": 81,
    "name": "Застосувати Артилерію",
    "description": "Потрібно: Застосувати 2 од. 'Артилерію'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 2,
    "main_reward": 21,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 82,
    "name": "Застосувати Артилерію",
    "description": "Потрібно: Застосувати 3 од. 'Артилерію'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 3,
    "main_reward": 31,
    "level_reward_points": 0.6,
    "currency_reward": 11
  },
  {
    "id": 83,
    "name": "Застосувати Гранати",
    "description": "Потрібно: Застосувати 1 од. 'Гранати'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 7,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 84,
    "name": "Застосувати Гранати",
    "description": "Потрібно: Застосувати 2 од. 'Гранати'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 2,
    "main_reward": 15,
    "level_reward_points": 0.5,
    "currency_reward": 5
  },
  {
    "id": 85,
    "name": "Застосувати Гранати",
    "description": "Потрібно: Застосувати 3 од. 'Гранати'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 3,
    "main_reward": 22,
    "level_reward_points": 0.6,
    "currency_reward": 8
  },
  {
    "id": 86,
    "name": "Застосувати Гранати",
    "description": "Потрібно: Застосувати 4 од. 'Гранати'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 4,
    "main_reward": 30,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 87,
    "name": "Стати ворожим до NPC",
    "description": "Потрібно: Стати ворожим до 1 од. 'NPC'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 88,
    "name": "Стати ворожим до NPC",
    "description": "Потрібно: Стати ворожим до 2 од. 'NPC'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 2,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 89,
    "name": "Стати ворожим до NPC",
    "description": "Потрібно: Стати ворожим до 3 од. 'NPC'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 3,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 90,
    "name": "Стати ворожим до NPC",
    "description": "Потрібно: Стати ворожим до 4 од. 'NPC'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 4,
    "main_reward": 48,
    "level_reward_points": 0.8,
    "currency_reward": 16
  },
  {
    "id": 91,
    "name": "Нанести шкоду з Артилерії",
    "description": "Потрібно: Нанести шкоду з 1 од. 'Артилерії'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 14,
    "level_reward_points": 0.5,
    "currency_reward": 5
  },
  {
    "id": 92,
    "name": "Нанести шкоду з Артилерії",
    "description": "Потрібно: Нанести шкоду з 2 од. 'Артилерії'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 2,
    "main_reward": 28,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 93,
    "name": "Нанести шкоду з Гранати",
    "description": "Потрібно: Нанести шкоду з 1 од. 'Гранати'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 10,
    "level_reward_points": 0.4,
    "currency_reward": 4
  },
  {
    "id": 94,
    "name": "Нанести шкоду з Гранати",
    "description": "Потрібно: Нанести шкоду з 2 од. 'Гранати'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 2,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 95,
    "name": "Нанести шкоду з Гранати",
    "description": "Потрібно: Нанести шкоду з 3 од. 'Гранати'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 3,
    "main_reward": 30,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 96,
    "name": "Нанести шкоду з Гранати",
    "description": "Потрібно: Нанести шкоду з 4 од. 'Гранати'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 4,
    "main_reward": 40,
    "level_reward_points": 0.7,
    "currency_reward": 14
  },
  {
    "id": 97,
    "name": "Нанести шкоду з Транспорту",
    "description": "Потрібно: Нанести шкоду з 1 од. 'Транспорту'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 1,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 98,
    "name": "Нанести шкоду з Транспорту",
    "description": "Потрібно: Нанести шкоду з 2 од. 'Транспорту'",
    "m_class": "Атака",
    "level": 1,
    "target_progress": 2,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 99,
    "name": "Нанести шкоду з Транспорту",
    "description": "Потрібно: Нанести шкоду з 3 од. 'Транспорту'",
    "m_class": "Атака",
    "level": 2,
    "target_progress": 3,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 100,
    "name": "Перехопити Точку",
    "description": "Потрібно: Перехопити 1 од. 'Точку'",
    "m_class": "Атака",
    "level": 3,
    "target_progress": 1,
    "main_reward": 75,
    "level_reward_points": 1.1,
    "currency_reward": 25
  },
  {
    "id": 101,
    "name": "Купити Предмет магазину",
    "description": "Потрібно: Купити 1 од. 'Предмет магазину'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 1,
    "main_reward": 4,
    "level_reward_points": 0.3,
    "currency_reward": 2
  },
  {
    "id": 102,
    "name": "Купити Предмет магазину",
    "description": "Потрібно: Купити 2 од. 'Предмет магазину'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 2,
    "main_reward": 8,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 103,
    "name": "Купити Предмет магазину",
    "description": "Потрібно: Купити 3 од. 'Предмет магазину'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 3,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 104,
    "name": "Купити Предмет магазину",
    "description": "Потрібно: Купити 4 од. 'Предмет магазину'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 4,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 105,
    "name": "Купити Предмет магазину",
    "description": "Потрібно: Купити 5 од. 'Предмет магазину'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 5,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 106,
    "name": "Купити Предмет магазину",
    "description": "Потрібно: Купити 6 од. 'Предмет магазину'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 6,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 107,
    "name": "Купити Предмет магазину",
    "description": "Потрібно: Купити 7 од. 'Предмет магазину'",
    "m_class": "Економіка",
    "level": 2,
    "target_progress": 7,
    "main_reward": 28,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 108,
    "name": "Купити Предмет магазину",
    "description": "Потрібно: Купити 8 од. 'Предмет магазину'",
    "m_class": "Економіка",
    "level": 2,
    "target_progress": 8,
    "main_reward": 32,
    "level_reward_points": 0.6,
    "currency_reward": 11
  },
  {
    "id": 109,
    "name": "Купити Предмет магазину",
    "description": "Потрібно: Купити 9 од. 'Предмет магазину'",
    "m_class": "Економіка",
    "level": 2,
    "target_progress": 9,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 110,
    "name": "Купити Найманців",
    "description": "Потрібно: Купити 1 од. 'Найманців'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 1,
    "main_reward": 8,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 111,
    "name": "Купити Найманців",
    "description": "Потрібно: Купити 2 од. 'Найманців'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 2,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 112,
    "name": "Купити Найманців",
    "description": "Потрібно: Купити 3 од. 'Найманців'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 3,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 113,
    "name": "Купити Транпорт з магазину",
    "description": "Потрібно: Купити 1 од. 'Транпорт з магазину'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 1,
    "main_reward": 8,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 114,
    "name": "Купити Транпорт з магазину",
    "description": "Потрібно: Купити 2 од. 'Транпорт з магазину'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 2,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 115,
    "name": "Купити Транпорт з магазину",
    "description": "Потрібно: Купити 3 од. 'Транпорт з магазину'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 3,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 116,
    "name": "Налагодити стосунки з NPC",
    "description": "Потрібно: Налагодити стосунки з 1 од. 'NPC'",
    "m_class": "Економіка",
    "level": 2,
    "target_progress": 1,
    "main_reward": 32,
    "level_reward_points": 0.6,
    "currency_reward": 11
  },
  {
    "id": 117,
    "name": "Налагодити стосунки з NPC",
    "description": "Потрібно: Налагодити стосунки з 2 од. 'NPC'",
    "m_class": "Економіка",
    "level": 3,
    "target_progress": 2,
    "main_reward": 64,
    "level_reward_points": 1,
    "currency_reward": 22
  },
  {
    "id": 118,
    "name": "Побудувати Ринок",
    "description": "Потрібно: Побудувати 1 од. 'Ринок'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 1,
    "main_reward": 6,
    "level_reward_points": 0.4,
    "currency_reward": 2
  },
  {
    "id": 119,
    "name": "Побудувати Покращення точки",
    "description": "Потрібно: Побудувати 1 од. 'Покращення точки'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 1,
    "main_reward": 6,
    "level_reward_points": 0.4,
    "currency_reward": 2
  },
  {
    "id": 120,
    "name": "Побудувати Покращення точки",
    "description": "Потрібно: Побудувати 2 од. 'Покращення точки'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 2,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 121,
    "name": "Побудувати Покращення точки",
    "description": "Потрібно: Побудувати 3 од. 'Покращення точки'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 3,
    "main_reward": 18,
    "level_reward_points": 0.6,
    "currency_reward": 6
  },
  {
    "id": 122,
    "name": "Накопити Валюту",
    "description": "Потрібно: Накопити 10 од. 'Валюту'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 10,
    "main_reward": 5,
    "level_reward_points": 0.4,
    "currency_reward": 2
  },
  {
    "id": 123,
    "name": "Накопити Валюту",
    "description": "Потрібно: Накопити 15 од. 'Валюту'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 15,
    "main_reward": 7,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 124,
    "name": "Накопити Валюту",
    "description": "Потрібно: Накопити 20 од. 'Валюту'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 20,
    "main_reward": 10,
    "level_reward_points": 0.4,
    "currency_reward": 4
  },
  {
    "id": 125,
    "name": "Накопити Валюту",
    "description": "Потрібно: Накопити 30 од. 'Валюту'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 30,
    "main_reward": 15,
    "level_reward_points": 0.5,
    "currency_reward": 5
  },
  {
    "id": 126,
    "name": "Накопити Залізо",
    "description": "Потрібно: Накопити 4 од. 'Залізо'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 4,
    "main_reward": 8,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 127,
    "name": "Накопити Залізо",
    "description": "Потрібно: Накопити 6 од. 'Залізо'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 6,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 128,
    "name": "Накопити Залізо",
    "description": "Потрібно: Накопити 8 од. 'Залізо'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 8,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 129,
    "name": "Накопити Залізо",
    "description": "Потрібно: Накопити 10 од. 'Залізо'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 10,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 130,
    "name": "Накопити Залізо",
    "description": "Потрібно: Накопити 12 од. 'Залізо'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 12,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 131,
    "name": "Подружитись NPC",
    "description": "Потрібно: Подружитись 1 од. 'NPC'",
    "m_class": "Економіка",
    "level": 2,
    "target_progress": 1,
    "main_reward": 32,
    "level_reward_points": 0.6,
    "currency_reward": 11
  },
  {
    "id": 132,
    "name": "Подружитись NPC",
    "description": "Потрібно: Подружитись 2 од. 'NPC'",
    "m_class": "Економіка",
    "level": 3,
    "target_progress": 2,
    "main_reward": 64,
    "level_reward_points": 1,
    "currency_reward": 22
  },
  {
    "id": 133,
    "name": "Торгувати з Гравцем",
    "description": "Потрібно: Торгувати з 1 од. 'Гравцем'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 1,
    "main_reward": 10,
    "level_reward_points": 0.4,
    "currency_reward": 4
  },
  {
    "id": 134,
    "name": "Торгувати з Гравцем",
    "description": "Потрібно: Торгувати з 2 од. 'Гравцем'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 2,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 135,
    "name": "Торгувати з NPC",
    "description": "Потрібно: Торгувати з 1 од. 'NPC'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 1,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 136,
    "name": "Торгувати з NPC",
    "description": "Потрібно: Торгувати з 2 од. 'NPC'",
    "m_class": "Економіка",
    "level": 2,
    "target_progress": 2,
    "main_reward": 32,
    "level_reward_points": 0.6,
    "currency_reward": 11
  },
  {
    "id": 137,
    "name": "Нанести шкоду Найманцями",
    "description": "Потрібно: Нанести шкоду 1 од. 'Найманцями'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 1,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 138,
    "name": "Нанести шкоду Найманцями",
    "description": "Потрібно: Нанести шкоду 2 од. 'Найманцями'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 2,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 139,
    "name": "Нанести шкоду Найманцями",
    "description": "Потрібно: Нанести шкоду 3 од. 'Найманцями'",
    "m_class": "Економіка",
    "level": 2,
    "target_progress": 3,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 140,
    "name": "Нанести шкоду Транспортом",
    "description": "Потрібно: Нанести шкоду 1 од. 'Транспортом'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 1,
    "main_reward": 18,
    "level_reward_points": 0.6,
    "currency_reward": 6
  },
  {
    "id": 141,
    "name": "Нанести шкоду Транспортом",
    "description": "Потрібно: Нанести шкоду 2 од. 'Транспортом'",
    "m_class": "Економіка",
    "level": 2,
    "target_progress": 2,
    "main_reward": 36,
    "level_reward_points": 0.7,
    "currency_reward": 12
  },
  {
    "id": 142,
    "name": "Нанести шкоду Транспортом",
    "description": "Потрібно: Нанести шкоду 3 од. 'Транспортом'",
    "m_class": "Економіка",
    "level": 2,
    "target_progress": 3,
    "main_reward": 54,
    "level_reward_points": 0.8,
    "currency_reward": 18
  },
  {
    "id": 143,
    "name": "Витратити Валюту",
    "description": "Потрібно: Витратити 10 од. 'Валюту'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 10,
    "main_reward": 5,
    "level_reward_points": 0.4,
    "currency_reward": 2
  },
  {
    "id": 144,
    "name": "Витратити Валюту",
    "description": "Потрібно: Витратити 15 од. 'Валюту'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 15,
    "main_reward": 7,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 145,
    "name": "Витратити Валюту",
    "description": "Потрібно: Витратити 20 од. 'Валюту'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 20,
    "main_reward": 10,
    "level_reward_points": 0.4,
    "currency_reward": 4
  },
  {
    "id": 146,
    "name": "Витратити Валюту",
    "description": "Потрібно: Витратити 30 од. 'Валюту'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 30,
    "main_reward": 15,
    "level_reward_points": 0.5,
    "currency_reward": 5
  },
  {
    "id": 147,
    "name": "Витратити Залізо",
    "description": "Потрібно: Витратити 4 од. 'Залізо'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 4,
    "main_reward": 8,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 148,
    "name": "Витратити Залізо",
    "description": "Потрібно: Витратити 6 од. 'Залізо'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 6,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 149,
    "name": "Витратити Залізо",
    "description": "Потрібно: Витратити 8 од. 'Залізо'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 8,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 150,
    "name": "Витратити Залізо",
    "description": "Потрібно: Витратити 10 од. 'Залізо'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 10,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 151,
    "name": "Витратити Залізо",
    "description": "Потрібно: Витратити 12 од. 'Залізо'",
    "m_class": "Економіка",
    "level": 1,
    "target_progress": 12,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 152,
    "name": "Здобути Артефакт",
    "description": "Потрібно: Здобути 1 од. 'Артефакт'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 153,
    "name": "Здобути Артефакт",
    "description": "Потрібно: Здобути 2 од. 'Артефакт'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 2,
    "main_reward": 48,
    "level_reward_points": 0.8,
    "currency_reward": 16
  },
  {
    "id": 154,
    "name": "Здобути Артефакт",
    "description": "Потрібно: Здобути 3 од. 'Артефакт'",
    "m_class": "Лут",
    "level": 3,
    "target_progress": 3,
    "main_reward": 72,
    "level_reward_points": 1.1,
    "currency_reward": 24
  },
  {
    "id": 155,
    "name": "Здобути Шматки мутантів",
    "description": "Потрібно: Здобути 1 од. 'Шматки мутантів'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 4,
    "level_reward_points": 0.3,
    "currency_reward": 2
  },
  {
    "id": 156,
    "name": "Здобути Шматки мутантів",
    "description": "Потрібно: Здобути 2 од. 'Шматки мутантів'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 2,
    "main_reward": 8,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 157,
    "name": "Здобути Шматки мутантів",
    "description": "Потрібно: Здобути 3 од. 'Шматки мутантів'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 3,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 158,
    "name": "Здобути Шматки мутантів",
    "description": "Потрібно: Здобути 4 од. 'Шматки мутантів'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 4,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 159,
    "name": "Здобути Шматки мутантів",
    "description": "Потрібно: Здобути 5 од. 'Шматки мутантів'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 5,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 160,
    "name": "Здобути Шматки мутантів",
    "description": "Потрібно: Здобути 6 од. 'Шматки мутантів'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 6,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 161,
    "name": "Здобути Шматки мутантів",
    "description": "Потрібно: Здобути 7 од. 'Шматки мутантів'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 7,
    "main_reward": 28,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 162,
    "name": "Здобути Шматки мутантів",
    "description": "Потрібно: Здобути 8 од. 'Шматки мутантів'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 8,
    "main_reward": 32,
    "level_reward_points": 0.6,
    "currency_reward": 11
  },
  {
    "id": 163,
    "name": "Здобути мисливський ніж",
    "description": "Потрібно: Здобути 1 од. 'мисливський ніж'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 6,
    "level_reward_points": 0.4,
    "currency_reward": 2
  },
  {
    "id": 164,
    "name": "Здобути мисливський ніж",
    "description": "Потрібно: Здобути 2 од. 'мисливський ніж'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 2,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 165,
    "name": "Здобути мисливський ніж",
    "description": "Потрібно: Здобути 3 од. 'мисливський ніж'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 3,
    "main_reward": 18,
    "level_reward_points": 0.6,
    "currency_reward": 6
  },
  {
    "id": 166,
    "name": "Вбити Мутантів 1 рів.",
    "description": "Потрібно: Вбити 1 од. 'Мутантів 1 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 4,
    "level_reward_points": 0.3,
    "currency_reward": 2
  },
  {
    "id": 167,
    "name": "Вбити Мутантів 1 рів.",
    "description": "Потрібно: Вбити 2 од. 'Мутантів 1 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 2,
    "main_reward": 8,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 168,
    "name": "Вбити Мутантів 1 рів.",
    "description": "Потрібно: Вбити 3 од. 'Мутантів 1 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 3,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 169,
    "name": "Вбити Мутантів 1 рів.",
    "description": "Потрібно: Вбити 4 од. 'Мутантів 1 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 4,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 170,
    "name": "Вбити Мутантів 1 рів.",
    "description": "Потрібно: Вбити 5 од. 'Мутантів 1 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 5,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 171,
    "name": "Вбити Мутантів 1 рів.",
    "description": "Потрібно: Вбити 6 од. 'Мутантів 1 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 6,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 172,
    "name": "Вбити Мутантів 1 рів.",
    "description": "Потрібно: Вбити 7 од. 'Мутантів 1 рів.'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 7,
    "main_reward": 28,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 173,
    "name": "Вбити Мутантів 1 рів.",
    "description": "Потрібно: Вбити 8 од. 'Мутантів 1 рів.'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 8,
    "main_reward": 32,
    "level_reward_points": 0.6,
    "currency_reward": 11
  },
  {
    "id": 174,
    "name": "Вбити Мутантів 2 рів.",
    "description": "Потрібно: Вбити 1 од. 'Мутантів 2 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 10,
    "level_reward_points": 0.4,
    "currency_reward": 4
  },
  {
    "id": 175,
    "name": "Вбити Мутантів 2 рів.",
    "description": "Потрібно: Вбити 2 од. 'Мутантів 2 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 2,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 176,
    "name": "Вбити Мутантів 2 рів.",
    "description": "Потрібно: Вбити 3 од. 'Мутантів 2 рів.'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 3,
    "main_reward": 30,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 177,
    "name": "Вбити Мутантів 2 рів.",
    "description": "Потрібно: Вбити 4 од. 'Мутантів 2 рів.'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 4,
    "main_reward": 40,
    "level_reward_points": 0.7,
    "currency_reward": 14
  },
  {
    "id": 178,
    "name": "Вбити Мутантів 2 рів.",
    "description": "Потрібно: Вбити 5 од. 'Мутантів 2 рів.'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 5,
    "main_reward": 50,
    "level_reward_points": 0.8,
    "currency_reward": 17
  },
  {
    "id": 179,
    "name": "Вбити Мутантів 3 рів.",
    "description": "Потрібно: Вбити 1 од. 'Мутантів 3 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 14,
    "level_reward_points": 0.5,
    "currency_reward": 5
  },
  {
    "id": 180,
    "name": "Вбити Мутантів 3 рів.",
    "description": "Потрібно: Вбити 2 од. 'Мутантів 3 рів.'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 2,
    "main_reward": 28,
    "level_reward_points": 0.6,
    "currency_reward": 10
  },
  {
    "id": 181,
    "name": "Вбити Мутантів 3 рів.",
    "description": "Потрібно: Вбити 3 од. 'Мутантів 3 рів.'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 3,
    "main_reward": 42,
    "level_reward_points": 0.7,
    "currency_reward": 14
  },
  {
    "id": 182,
    "name": "Вбити Мутантів 3 рів.",
    "description": "Потрібно: Вбити 4 од. 'Мутантів 3 рів.'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 4,
    "main_reward": 56,
    "level_reward_points": 0.9,
    "currency_reward": 19
  },
  {
    "id": 183,
    "name": "дійти до центрального сектора",
    "description": "Потрібно: дійти до 1 од. 'центрального сектора'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 15,
    "level_reward_points": 0.5,
    "currency_reward": 5
  },
  {
    "id": 184,
    "name": "Використати мисливський ніж",
    "description": "Потрібно: Використати 1 од. 'мисливський ніж'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 9,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 185,
    "name": "Використати мисливський ніж",
    "description": "Потрібно: Використати 2 од. 'мисливський ніж'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 2,
    "main_reward": 18,
    "level_reward_points": 0.6,
    "currency_reward": 6
  },
  {
    "id": 186,
    "name": "Використати мисливський ніж",
    "description": "Потрібно: Використати 3 од. 'мисливський ніж'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 3,
    "main_reward": 27,
    "level_reward_points": 0.7,
    "currency_reward": 9
  },
  {
    "id": 187,
    "name": "Обікрасти склад",
    "description": "Потрібно: Обікрасти 1 од. 'склад'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 24,
    "level_reward_points": 0.7,
    "currency_reward": 8
  },
  {
    "id": 188,
    "name": "Обікрасти лут дроном",
    "description": "Потрібно: Обікрасти 1 од. 'лут дроном'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 4,
    "level_reward_points": 0.3,
    "currency_reward": 2
  },
  {
    "id": 189,
    "name": "Обікрасти лут дроном",
    "description": "Потрібно: Обікрасти 2 од. 'лут дроном'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 2,
    "main_reward": 8,
    "level_reward_points": 0.4,
    "currency_reward": 3
  },
  {
    "id": 190,
    "name": "Обікрасти лут дроном",
    "description": "Потрібно: Обікрасти 3 од. 'лут дроном'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 3,
    "main_reward": 12,
    "level_reward_points": 0.5,
    "currency_reward": 4
  },
  {
    "id": 191,
    "name": "Обікрасти лут дроном",
    "description": "Потрібно: Обікрасти 4 од. 'лут дроном'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 4,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 192,
    "name": "Побудувати склад",
    "description": "Потрібно: Побудувати 1 од. 'склад'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 6,
    "level_reward_points": 0.4,
    "currency_reward": 2
  },
  {
    "id": 193,
    "name": "Обмінятись з NPC",
    "description": "Потрібно: Обмінятись з 1 од. 'NPC'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 16,
    "level_reward_points": 0.5,
    "currency_reward": 6
  },
  {
    "id": 194,
    "name": "Обмінятись з NPC",
    "description": "Потрібно: Обмінятись з 2 од. 'NPC'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 2,
    "main_reward": 32,
    "level_reward_points": 0.6,
    "currency_reward": 11
  },
  {
    "id": 195,
    "name": "Обмінятись з NPC",
    "description": "Потрібно: Обмінятись з 3 од. 'NPC'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 3,
    "main_reward": 48,
    "level_reward_points": 0.8,
    "currency_reward": 16
  },
  {
    "id": 196,
    "name": "Дослідити Аномалії 1 рів.",
    "description": "Потрібно: Дослідити 1 од. 'Аномалії 1 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 197,
    "name": "Дослідити Аномалії 1 рів.",
    "description": "Потрібно: Дослідити 2 од. 'Аномалії 1 рів.'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 2,
    "main_reward": 40,
    "level_reward_points": 0.7,
    "currency_reward": 14
  },
  {
    "id": 198,
    "name": "Дослідити Аномалії 2 рів.",
    "description": "Потрібно: Дослідити 1 од. 'Аномалії 2 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 199,
    "name": "Дослідити Аномалії 2 рів.",
    "description": "Потрібно: Дослідити 2 од. 'Аномалії 2 рів.'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 2,
    "main_reward": 40,
    "level_reward_points": 0.7,
    "currency_reward": 14
  },
  {
    "id": 200,
    "name": "Дослідити Аномалії 3 рів.",
    "description": "Потрібно: Дослідити 1 од. 'Аномалії 3 рів.'",
    "m_class": "Лут",
    "level": 1,
    "target_progress": 1,
    "main_reward": 20,
    "level_reward_points": 0.6,
    "currency_reward": 7
  },
  {
    "id": 201,
    "name": "Дослідити Аномалії 3 рів.",
    "description": "Потрібно: Дослідити 2 од. 'Аномалії 3 рів.'",
    "m_class": "Лут",
    "level": 2,
    "target_progress": 2,
    "main_reward": 40,
    "level_reward_points": 0.7,
    "currency_reward": 14
  }
]
